# Numpy Array

In [1]:
import numpy as np

In [3]:
temp_O_coord = [0.0, -0.2, 1.4]
translation_vector = [0.0, 0.1, -0.3]
print(temp_O_coord + translation_vector)

[0.0, -0.2, 1.4, 0.0, 0.1, -0.3]


In [11]:
O_coord = np.array(temp_O_coord)
print(type(temp_O_coord))
print(type(O_coord))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
print(O_coord + translation_vector)

[ 0.  -0.1  1.1]


In [13]:
print(O_coord*0.529)

[ 0.     -0.1058  0.7406]


In [14]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0])

In [15]:
print(b-a)
print(a**2)
print(np.sum(a),np.sum(b))
print(np.sqrt(a),np.sqrt(4.0))

[3. 3. 3.]
[1. 4. 9.]
6.0 15.0
[1.         1.41421356 1.73205081] 2.0


In [16]:
H_coord = np.array([0.0,0.6,0.9])

In [20]:
dist = np.sqrt(np.sum((O_coord - H_coord)**2))
print(F'The bond length of O-H is {dist} in Angstroms.')

The bond length of O-H is 0.9433981132056604 in Angstroms.
